parameters:
#    unknownbliss_michael_cullum_com.example.class: Unknownbliss\MichaelCullumComBundle\Example

services:
#    unknownbliss_michael_cullum_com.example:
#        class: %unknownbliss_michael_cullum_com.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
